# C++
[[language]]
name = "cpp"
auto-format = true
indent = { tab-width = 4, unit = "    " }

# Rust
[[language]]
name = "rust"
auto-format = true
indent = { tab-width = 4, unit = "    " }

# Go
[[language]]
name = "go"
auto-format = true
indent = { tab-width = 4, unit = "    " }

# Python
[[language]]
name = "python"
auto-format = true
indent = { tab-width = 4, unit = "    " }
language-servers = [
  "pyright",
  { name = "ty", only-features = [
    "diagnostics",
    "inlay-hints",
  ] },
  { name = "ruff", only-features = [
    "diagnostics",
    "code-action",
    "format",
  ] },
]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.ty]
command = "ty"
args = ["server"]

[language-server.ruff]
command = "ruff"
args = ["server", "--preview"]

# Bash
[[language]]
name = "bash"
auto-format = true
indent = { tab-width = 4, unit = "    " }

# JSON
[[language]]
name = "json"
auto-format = true
indent = { tab-width = 2, unit = "    " }

# TOML
[[language]]
name = "toml"
auto-format = true
indent = { tab-width = 4, unit = "    " }
formatter = { command = "taplo", args = ["fmt", "-"] }
