inherits = "carbon"

"attribute" = { fg = "blue60", modifiers = [""] }

"comment" = { fg = "gray50", modifiers = [""] }
"comment.block.documentation" = { fg = "gray50", modifiers = [""] }
"comment.line.documentation" = { fg = "gray50", modifiers = [""] }

"keyword.function" = { fg = "teal40", modifiers = ["bold", ""] }
"keyword.storage.modifier" = { fg = "purple40", modifiers = [""] }

"namespace" = { fg = "teal40", modifiers = [""] }

"type" = { fg = "cyan30", modifiers = [""] }

"ui.background" = {}
"ui.virtual.inlay-hint" = { fg = "#646f69" }

"variable.parameter" = { fg = "magenta40", modifiers = [""] }
"variable.other.member" = { fg = "magenta30", modifiers = [""] }

"label" = { fg = "blue40", modifiers = [""] }
