inherits = "carbon"

"ui.background" = {}

"attribute" = { fg = "blue60", modifiers = [] }

"type" = { fg = "cyan30", modifiers = [] }

"comment" = { fg = "gray40", modifiers = [] }
"comment.block.documentation" = { fg = "gray40", modifiers = [] }
"comment.line.documentation" = { fg = "gray40", modifiers = [] }

"variable.parameter" = { fg = "magenta40", modifiers = [] }
"variable.other.member" = { fg = "magenta30", modifiers = [] }

"label" = { fg = "blue40", modifiers = [] }

"keyword.function" = { fg = "teal40", modifiers = ["bold"] }
"keyword.storage.modifier" = { fg = "purple40", modifiers = [] }

"namespace" = { fg = "teal40", modifiers = [] }

"markup.italic" = { modifiers = [] }
"markup.quote" = { fg = "green30", modifiers = [] }
